jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

server:
 port: 5000
# error:
#    whitelabel:
#      enabled: false
# amezone: url: jdbc:mysql://18.222.92.183:3306/support_api_db
# url: jdbc:mysql://localhost:3306/backend_api_db
# amezone: root/Cheng$A:21@!
# localhost: root/chengsoft
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_api_db
    password: Cheng$A:21@!
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false---


